### ISSUE TITLE
404 Error when showing list of previous API documentations

### ISSUE THREAD

**Issue by rlam1** [liballeg/liballeg.github.io#1]
When a user tries to access http://alleg.sourceforge.net/a5docs/ from http://liballeg.org/api.html to see the docs for older versions of the library, the new host no longer shows a standard FTP file tree as SourceForge did. The files are there, it just need to have a listing of the directories manually done.

**Comment by SiegeLord** [comment]
I've added a horrible looking index page. Eventually we'll get a new website, but for now at least it's not a 404 error.

Thanks for reporting this!
