### ISSUE TITLE
✨ Feature Request: Hotkey for Search Box

### ISSUE THREAD

**Issue by MarkOates** [liballeg/liballeg.github.io#4]
It would be nice to have a hotkey to have the keyboard focus on the search bar.  In most software (for example GitHub), the standard key to focus on search is the '`/`' key.

![Allegro 5 reference manual 2020-12-18 21-12-01](https://user-images.githubusercontent.com/772949/102678349-cc547c00-4175-11eb-900b-a625bd2eb353.png)

**Comment by MarkOates** [comment]
(Copied from [my post on allegro.cc](https://www.allegro.cc/forums/thread/618381/1049583#target)):

@SiegeLord  I meant to follow up on this.  This should be the forward slash key '<code>/</code>'. A few examples to support this:

* Github: <code>/</code> sets the focus to the search bar
* Google: <code>/</code> sets the focus to the search bar
* Gmail, Google Calendar, etc: <code>/</code> [search for messages](https://blog.hubspot.com/sales/gmail-keyboard-shortcuts), events
* Hotmail: <code>/</code> [Search your email messages](https://www.cnet.com/how-to/how-to-use-keyboard-shortcuts-with-hotmail)
* MacOS: <code>Command</code>+<code>Shift</code>+<code>/</code> [opens the MacOS menu bar search](https://www.macrumors.com/how-to/use-the-macos-help-menu/#:~:text=You%20can%20use%20the%20keyboard,subject%20you%20need%20help%20with) box for menu items.
* Google Docs: <code>Alt</code>+<code>/</code> (Win), <code>Option</code>+<code>/</code> (MacOS) to [search menus](https://support.google.com/docs/answer/179738?co=GENIE.Platform%3DDesktop&hl=en#:~:text=To%20search%20the%20menus%2C%20press,also%20use%20menu%20access%20keys)
* Shopify Internal: Uses <code>Shift</code>+<code>/</code> same UX pattern for focus on search

I was lazy, so I didn't cite them all.  But! Historically, this key comes from a lot of terminal programs that use <code>/</code> for search. I'll cite [Vim's use for regex search](https://linuxize.com/post/vim-search), [<code>man</code>'s use of <code>/</code> to start a search](https://askubuntu.com/questions/20752/how-can-i-search-within-a-manpage), and it's also used when you looking through results in a [terminal's `less` command](https://www.thegeekstuff.com/2010/02/unix-less-command-10-tips-for-effective-navigation). I'm sure there are many more.

Since it was so common and ubiquitous for terminal applications, it made its way up to the web applications for that same bahavior.  A few of these (GMail, Google Cal) even use the `j/k` keys to move up/down, which is also common behavior for terminal programs like vim/less/man/etc.  You might need to turn on keyboard shortcuts in settings for some of these.

Plus, I even map the <code>/</code> key to search in [hexagon](https://github.com/MarkOates/hexagon/blob/master/src/Hexagon/System/EventController.cpp#L364-L366).

**Comment by SiegeLord** [comment]
So the reason I chose `S` over `/` is that `/` in Firefox opens up a search menu, and I didn't want to override that. I stole `S` specifically from Rust's documentation generator specifically. I guess those two are in a minority though, I don't mind changing it, adding `/` as an alternative or keeping it as is etc.

I'll accept a PR :).
