### ISSUE TITLE
liballeg.org domain

### ISSUE THREAD

**Issue by MarkOates** [liballeg/liballeg.github.io#7]
@troutsneeze, we're all trying to contact you about liballeg.org.  It's displaying some weird content, can you please address these issues and return it to the allegro library website?

The domain is for the allegro library - We're all concerned and want to know why you're doing this.

**Comment by EdgarReynaldo** [comment]
Trent Buddy, what are you doing man? Taking revenge on allegro is like programming in C++. You're bound to shoot yourself in the foot at some point. Don't go out like this man. Your personal gain is not more important than the allegro library you worked so hard to yourself create. Please return liballeg.org to it's normal content. Elias has been paying for the website for the last 10 years and taking it from him now is just rude and immature. Take your meds dude. (From a fellow schizophrenic)
